import Head from 'next/head'
import Link from 'next/link'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {faReact, faHtml5, faCss3, faFigma, faPhp, faLaravel, faPython, faNodeJs} from '@fortawesome/free-brands-svg-icons'
import { faTwitter, faFacebook, faInstagram } from '@fortawesome/free-brands-svg-icons'
import { faDatabase } from '@fortawesome/free-solid-svg-icons'
import styles from '../styles/Home.module.css'
import ServicesSection from '../components/servicesSection'


const ServiceSectionThemes = {
  darkTheme: {
    backgroundColor: "#222",
    foregroundColor: "#fff"
  },
  lightGrayTheme: {
    backgroundColor: "rgba(169,169,169, 0.2)",
    foregroundColor: "#222"
  }
}

const frontEndSectionIcons = [faReact, faHtml5, faFigma, faCss3];
const backEndSectionIcons = [faPhp, faLaravel, faPython, faNodeJs];
const databaseSectionIcons = [faDatabase, faDatabase, faDatabase, faDatabase]


const servicesSection = {
  frontEndSection: {
    title: "Learn Frontend Web Design with Us",
    content: "Our team offers the best frontend web design in the industry in Africa. We can build clean and elegant user interfaces and provide better user experiences"
  },

  backEndSection: {
    title: "Learn Backend Programming with Us",
    content: "Our team offers the best backend frameworks in the industry in Africa. We write clean and elegant backend code that will integrate with frontend frameworks"
  },

  databaseSection: {
    title: "Learn Database Management with Us",
    content: "Our team offers accelerated database management expertise you can find in Africa. We can manage your databases with provision for scability "
  }
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header className={styles.header}>
        <div className={styles.headerContainer}>
          <div className={styles.brandNameContainer}>
            <Link href='/'>
              <a className={styles.brandName}>KORAL NG</a>
            </Link>
          </div>
          <div className={styles.topNavBar}>
            <Link href="./products">
              <a className={styles.navLink}>Products</a>
            </Link>

            <Link href="./services">
              <a className={styles.navLink}>Services</a>
            </Link>

            <Link href="./investors">
              <a className={styles.navLink}>Investors</a>
            </Link>
          </div>
          <div className={styles.logInBtnContainer}>
            <button className={styles.logInBtn}>Log in</button>
          </div>
        </div>
      </header>

      <div className={styles.bannerContainer}>
        <h3 className={styles.bannerTitle}>KORAL NG</h3>
        <p className={styles.bannerDesc}>Providing tech solutions for africa</p>
        <Link href="/learn-more">
          <a className={styles.learnMoreNavLink}>Learn more</a>
        </Link>
      </div>

      <ServicesSection title={servicesSection.frontEndSection.title} content={servicesSection.frontEndSection.content} theme={ServiceSectionThemes.darkTheme} icons={frontEndSectionIcons}/>
      <ServicesSection title={servicesSection.backEndSection.title} content={servicesSection.backEndSection.content} reversedLayout theme={ServiceSectionThemes.lightGrayTheme} icons={backEndSectionIcons}/>
      <ServicesSection title={servicesSection.databaseSection.title} content={servicesSection.databaseSection.content} theme={ServiceSectionThemes.darkTheme} icons={databaseSectionIcons}/>

      {/* <div className={styles.frontEndSection}>
        <div className={styles.frontEndContainer}>
          <div className={styles.frontEndSectionContent}>
            <h3 className={styles.frontEndSectionContentTitle}>
            Learn Frontend Web Design with Us
            </h3>

            <p className={styles.frontEndSectionContentText}>
            Our team offers the best frontend web design in the industry in Africa. 
            We can build clean and elegan user interfaces and provide better user experiences
            </p>

            <button className={styles.frontEndSectionContentBtn}>
              Get Started with us
            </button>
          </div>
          <div className={styles.frontEndSectionIcons}>
            <div className={styles.frontEndSectionBrandIconOne}>
              <FontAwesomeIcon icon={faReact} size="4x" color="white"/>
            </div>

            <div className={styles.frontEndSectionBrandIconTwo}>
              <FontAwesomeIcon icon={faHtml5} size="4x" color="white"/>
            </div>
            <div className={styles.frontEndSectionBrandIconThree}>
              <FontAwesomeIcon icon={faFigma} size="4x" color="white"/>
            </div>
            <div className={styles.frontEndSectionBrandIconFour}>
              <FontAwesomeIcon icon={faCss3} size="4x" color="white"/>
            </div>
          </div>
        </div>
      </div>

      <div className={styles.frontEndSection}>
        <div className={styles.frontEndContainer}>
          
          <div className={styles.frontEndSectionIcons}>
            <div className={styles.frontEndSectionBrandIconOne}>
              <FontAwesomeIcon icon={faReact} size="4x" color="white"/>
            </div>

            <div className={styles.frontEndSectionBrandIconTwo}>
              <FontAwesomeIcon icon={faHtml5} size="4x" color="white"/>
            </div>
            <div className={styles.frontEndSectionBrandIconThree}>
              <FontAwesomeIcon icon={faFigma} size="4x" color="white"/>
            </div>
            <div className={styles.frontEndSectionBrandIconFour}>
              <FontAwesomeIcon icon={faCss3} size="4x" color="white"/>
            </div>
          </div>
          
          <div className={styles.frontEndSectionContent}>
            <h3 className={styles.frontEndSectionContentTitle}>
            Learn Backend Programming with Us
            </h3>

            <p className={styles.frontEndSectionContentText}>
            Our team offers the best backend frameworks in the industry in Africa. 
            We write clean and elegant backend code that will integrate with frontend frameworks
            </p>

            <button className={styles.frontEndSectionContentBtn}>
              Get Started with us
            </button>
          </div>

        </div>
      </div>

      <div className={styles.frontEndSection}>
        <div className={styles.frontEndContainer}>
          <div className={styles.frontEndSectionContent}>
            <h3 className={styles.frontEndSectionContentTitle}>
            Learn Database Management with Us
            </h3>

            <p className={styles.frontEndSectionContentText}>
            Our team offers accelerated database management expertise you can find in Africa. 
            We can manage your databases with provision for scability 
            </p>

            <button className={styles.frontEndSectionContentBtn}>
              Get Started with us
            </button>
          </div>
          <div className={styles.frontEndSectionIcons}>
            <div className={styles.frontEndSectionBrandIconOne}>
              <FontAwesomeIcon icon={faReact} size="4x" color="white"/>
            </div>

            <div className={styles.frontEndSectionBrandIconTwo}>
              <FontAwesomeIcon icon={faHtml5} size="4x" color="white"/>
            </div>
            <div className={styles.frontEndSectionBrandIconThree}>
              <FontAwesomeIcon icon={faFigma} size="4x" color="white"/>
            </div>
            <div className={styles.frontEndSectionBrandIconFour}>
              <FontAwesomeIcon icon={faCss3} size="4x" color="white"/>
            </div>
          </div>
        </div>
      </div> */}

      <footer className={styles.footer}>
        <div className={styles.footerContainer}>
          <div className={styles.footerContent}>
           
            <div className={styles.footerContentItem}>
              <h3>COMPANY</h3>
              <ul className={styles.footerContentListItems}>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>What we do</a> 
                  </Link>
                </li>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>Our Leadership</a> 
                  </Link>
                </li>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>Careers</a> 
                  </Link>
                </li>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>FAQs</a> 
                  </Link>
                </li>
              </ul>
            </div>

            <div className={styles.footerContentItem}>
              <h3>ABOUT US</h3>
              <ul className={styles.footerContentListItems}>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>Terms and Conditions</a> 
                  </Link>
                </li>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>Privacy Policy</a> 
                  </Link>
                </li>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>Cookie Policy</a> 
                  </Link>
                </li>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>Complaints</a> 
                  </Link>
                </li>
              </ul>
            </div>

            <div className={styles.footerContentItem}>
              <h3>SUPPORT</h3>
              <ul className={styles.footerContentListItems}>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>Email</a> 
                  </Link>
                </li>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>ngkoral@gmail.com</a> 
                  </Link>
                </li>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>Mobile No:</a> 
                  </Link>
                </li>
                <li className={styles.footerContentListItem}>
                  <Link href="/">
                    <a>+234-(0)-7051557983</a> 
                  </Link>
                </li>
              </ul>
            </div>
        


          </div>

           

          <footer className={styles.footerBottom}>
            <div className={styles.footerCopyright}>
              <span>&copy;2021. Koral NG</span>
            </div>

            <div className={styles.socialHandleContainer}>
              <div>
                <Link href="https://www.facebook.com/benhoorkwap">
                  <a><FontAwesomeIcon icon={faFacebook} size="2x" color="#222"></FontAwesomeIcon></a>
                </Link>
              </div>

              <div>
                <Link href="https://www.twitter.com/bbuetsen">
                  <a><FontAwesomeIcon icon={faTwitter} size="2x" color="#222"></FontAwesomeIcon></a>
                </Link>
              </div>

              <div>
                <Link href="https://www.instagram.com/bbuetsen">
                  <a><FontAwesomeIcon icon={faInstagram} size="2x" color="#222"></FontAwesomeIcon></a>
                </Link>
              </div>
            </div>
          </footer>
        </div>
      </footer>

    </div>
  )
}
